name: CI
on: push
jobs:
  dockerfile-style:
    name: "Lint Dockerfile"
    uses: PlaceOS/.github/.github/workflows/dockerfile-style.yml@main

  nginx-style:
    runs-on: ubuntu-latest
    name: "Lint ${{ matrix.file }}"
    container: node:12
    strategy:
      matrix:
        file:
          - config/nginx.conf
          - config/nginx-nossl.conf
    steps:
      - uses: actions/checkout@v2
      - run: npx nginx-linter --include '${{ matrix.file }}'
